// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tutorial

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   string
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID sql.NullInt64
	// Can be negative or positive
	Amount    string
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID sql.NullInt64
	ToAccountID   sql.NullInt64
	// Can only be positive
	Amount    string
	CreatedAt time.Time
}
